services:
  backend:
    build:
      context: https://github.com/rooholaZamani/lms.git#main:backend
      dockerfile: Dockerfile
    container_name: lms-backend
    ports:
      - "8080:8080"
    volumes:
      - /srv/lms/data:/app/data
      - /srv/lms/uploads:/app/uploads
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SERVER_PORT=8080
      - JAVA_OPTS=-Xmx512m -Xms256m
    networks:
      - lms-network
    restart: unless-stopped

  frontend:
    build:
      context: https://github.com/rooholaZamani/lms_front.git#main:frontend
      dockerfile: Dockerfile
    container_name: lms-frontend
    ports:
      - "80:80"
    environment:
      - NODE_ENV=production
    networks:
      - lms-network
    restart: unless-stopped
    depends_on:
      - backend

networks:
  lms-network:
    driver: bridge
    name: lms-network

volumes:
  app-data:
    driver: local